// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A user-defined action that appears in the menu bar popup.
 */
export type Action = {
  id: string;
  /**
   * Display name shown in the menu bar popup
   */
  name: string;
  /**
   * ID of the provider to use
   */
  providerId: string;
  /**
   * User-facing instruction sent to the LLM
   */
  userPrompt: string;
  /**
   * Optional model override (overrides provider default)
   */
  model?: string;
};
