// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Action } from "./Action";
import type { AppSettings } from "./AppSettings";
import type { Provider } from "./Provider";

/**
 * Root configuration object stored in ~/Library/Application Support/llm-actions/config.json
 */
export type AppConfig = {
  providers: Array<Provider>;
  actions: Array<Action>;
  settings: AppSettings;
};
