// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Global application settings.
 */
export type AppSettings = {
  showNotificationOnComplete: boolean;
  maxTokens: number;
  historyEnabled: boolean;
};
