// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Global application settings.
 */
export type AppSettings = {
  showNotificationOnComplete: boolean;
  /**
   * Whether Clipwise should be registered as a macOS login item.
   */
  startAtLogin: boolean;
  maxTokens: number;
  historyEnabled: boolean;
  /**
   * Older saved configs predate onboarding and must not be interrupted.
   * New configs use `Default`, which deliberately starts incomplete.
   */
  onboardingCompleted: boolean;
};
