// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A single history entry recording a text transformation.
 */
export type HistoryEntry = {
  id: string;
  /**
   * ISO 8601 timestamp
   */
  timestamp: string;
  /**
   * Name of the action that was run
   */
  actionName: string;
  /**
   * Name of the provider that was used
   */
  providerName: string;
  /**
   * Input text (truncated for storage)
   */
  inputText: string;
  /**
   * Output text (truncated for storage)
   */
  outputText: string;
  /**
   * Whether the transformation succeeded
   */
  success: boolean;
};
