// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProviderType } from "./ProviderType";

/**
 * A configured LLM provider (API or CLI).
 */
export type Provider = {
  id: string;
  name: string;
  type: ProviderType;
  /**
   * For API providers: base endpoint URL
   */
  endpoint?: string;
  /**
   * For API providers: API key
   */
  apiKey?: string;
  /**
   * For API providers: extra headers
   */
  headers?: Record<string, string> | undefined;
  /**
   * Default model name for this provider
   */
  defaultModel?: string;
  /**
   * For CLI providers: command to execute
   */
  command?: string;
  /**
   * For CLI providers: arguments (model/flags)
   */
  args?: string[] | undefined;
};
